[market]
mcycle_price = "0.000000000007"
mcycle_price_stake_token = "0.0001"
peak_prove_khz = 800
max_mcycle_limit = 14400
max_journal_bytes = 10000
min_deadline = 100
lookback_blocks = 300
max_stake = "5"
max_file_size = 50_000_000
max_concurrent_proofs = 1
max_concurrent_preflights = 2  # Double the concurrency to handle more orders
max_critical_task_retries = 10
lockin_priority_gas = 5000000
balance_warn_threshold = "0.1"
balance_error_threshold = "0.05"
stake_balance_warn_threshold = "10"
stake_balance_error_threshold = "5"
min_lock_out_time = 14

[prover]
bonsai_r0_zkvm_ver = "2.1.0"
status_poll_retry_count = 3
status_poll_ms = 1000
req_retry_count = 3
req_retry_sleep_ms = 500
proof_retry_count = 8
proof_retry_sleep_ms = 5000

[batcher]
batch_max_time = 1000
min_batch_size = 1
block_deadline_buffer_secs = 180
txn_timeout = 100
single_txn_fulfill = true
withdraw = false
max_submission_attempts = 10